### ISSUE TITLE
Running the module gives error on Raspbian

### ISSUE THREAD

**Issue by ioncorimenia** [FullScreenShenanigans/shenanigans-manager#26]
I ran the commands in the usage section of the readme, but it just errors out:

```jtvjan@localhost:~ $ sudo npm install -g shenanigans-manager
# Runs without errors
jtvjan@localhost:~ $ shenanigans-manager --help
: No such file or directory
```

The only other modules I installed globally are gulp, n and npm. I'm using Raspbian 8.0 Jessie on a Raspberry Pi 3B as a headless server.

**Comment by JoshuaKGoldberg** [comment]
Hi @jtvjan - sorry for the delay. This is only really tested on Windows. I'd be surprised if it ran on Mac/*nix without error.

**Comment by JoshuaKGoldberg** [comment]
Closing this for housekeeping purposes. If you still need this, let me know and I can take another look!
